### ISSUE TITLE
Want more than 5 records from calendar-month-array 

### ISSUE THREAD

**Issue by shivani-anilabs** [krazylek/calendar-month-array#1]
I was using calendar-month-array package to get array of weeks. But i am getting only 5 records at a time. Is there any prop or param that i can pass to get more than 5 records ?

**Comment by krazylek** [comment]
The number of week records is adjusted automatically, so normally you should not worry about it. Most of the time you will find only 5 weeks in a month, some require 4 or 6 depending on first day of month. 
These week record are Array themselves, containing the list of days.

Does it answer your question?
